name: ROS 2 Build and Push to GHCR

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ghcr.io/rudolfkalman/ros-dev:jazzy

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Pull base image
        run: docker pull ${{ env.IMAGE_NAME }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (Tags/Labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/rudolfkalman/rescuerobot2026
          tags: |
            type=ref,event=branch
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/master' }}
            type=sha,prefix={{date 'YYYYMMDD-HHmm'}}-

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          load: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

          cache-from: |
            type=registry,ref=${{ env.IMAGE_NAME }}
            type=gha

          cache-to: type=gha,mode=max

      - name: Test Colcon Build
        run: |
          IMAGE_TAG=$(echo "${{ steps.meta.outputs.tags }}" | head -n 1)

          docker run --rm \
            -v ${{ github.workspace }}:/ws \
            -w /ws \
            --user root \
            $IMAGE_TAG \
            /bin/bash -c "
              chown -R root:root /ws &&
              source /opt/ros/jazzy/setup.sh &&
              colcon build --symlink-install \
                --cmake-args -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
                --packages-ignore \$(ls src | grep '^ext_' || true) &&
              find src -name '*.cpp' | grep -v 'src/ext_' | while read file; do
                pkg=\$(echo \"\$file\" | cut -d/ -f2)
                clang-tidy \"\$file\" -p \"build/\$pkg\" --config-file=.clang-tidy
              done
            "
