name: ROS 2 Build Check

on:
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t rescue-robot-ci .

      - name: Run Colcon Build in Container
        run: |
          docker run --rm -v ${{ github.workspace }}:/ws -w /ws rescue-robot-ci /bin/bash -c "
            . /opt/ros/jazzy/setup.sh &&
            colcon build --symlink-install
          "
